spring.application.name=automata

# Hibernate Config
spring.jpa.properties.hibernate.jdbc.batch_size=50

spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Postgres DB Config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway config (production-only)
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration

# S3 (RustFS) Config
spring.cloud.aws.region.static=${RUSTFS_REGION}
spring.cloud.aws.credentials.access-key=${RUSTFS_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${RUSTFS_SECRET_KEY}
spring.cloud.aws.s3.endpoint=${RUSTFS_ENDPOINT}
spring.cloud.aws.s3.path-style-access-enabled=true

# RabbitMQ Config
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}

# App Tmp File Storage Config:
com.automata.files.tmp.location=${TMP_FILES_PATH}

# Logging
logging.level.com.automata=debug