@startuml
actor "User" as user
box "Central Server"
participant "Cental Service" as api
database postgres
database redis
queue "Main Global" as mainq
queue "Global Network Routines" as networkq
queue "Host Short Running Routines" as shortq
queue "Host Long Running Routines" as longq
end box


autonumber "<b>[00]"
user -> api : initiate type:QUEUED run
api -> postgres : store run details

alt is Network
alt isEagerRun
api -> networkq : publishConfigWithHighPriority()
api -> mainq : publishPointerWithHighPriority()
else isLazyRun
api -> networkq : publishConfig()
api -> mainq : publishPointer()
end
api --> user : return run config
end

alt is HTTP

alt is HTTP Short
alt isEagerRun
api -> shortq: publishConfigWithHighPriority()
else isLazyRun
api -> shortq: publishConfig()
end
else is HTTP Long
alt isEagerRun
api -> longq: publishConfigWithHighPriority()
else isLazyRun
api -> longq: publishConfig()
end
end

api --> user : return run config

ref over api: SYNC_HTTP_RUN_OPERATIONS

end
@enduml