@startuml
actor "User" as user
box "Central Server"
participant "Central Service" as api
database postgres
queue "Main Global" as mainq
end box

autonumber "<b>[00]"
user -> api : initiate type:QUEUED run
api -> postgres : store run config
api -> postgres : store run args

alt isEagerRun
api -> mainq : publishPointerWithHighPriority()
else isLazyRun
api -> mainq : publishPointer()
end
api --> user : return run config

@enduml