@startuml
actor "User" as user
box "Central Server"
participant "Cental Service" as api
database postgres
database redis
queue "Main Global" as mainq
queue "Global Network Routines" as networkq
queue "Program Routines" as programq
end box


autonumber "<b>[00]"
user -> api : initiate type:QUEUED run
api -> postgres : store run details

alt is Network
alt isEagerRun
api -> networkq : publishConfigWithHighPriority()
api -> mainq : publishPointerWithHighPriority()
else isLazyRun
api -> networkq : publishConfig()
api -> mainq : publishPointer()
end
api --> user : return run config
end

alt is HTTP
alt isEagerRun
api -> programq: publishConfigWithHighPriority()
else isLazyRun
api -> programq: publishConfig()
end

api --> user : return run config

ref over api: SYNC_HTTP_RUN_OPERATIONS


end
@enduml