
@startuml
box "Central Server"
participant "Central Service" as api
database postgres
database redis
queue "Main Global" as mainq
end box



api -> postgres : GetHighPriorityIfFoundElseOldestRoutineToQueue("PROGRAM")
note right
Here "PROGRAM" is the program which is relative to the action which has caused the sync
So if for example a routine finished in the program X then "X" will be the "PROGRAM" here
end note
postgres --> api: return routine run details

api -> postgres : GetWideRoutinesRate("PROGRAM")
note right #LightGreen
<b>VERY IMP NOTE
When calculating current narrow running rate to determine whether we are able to run a new routine:
rate of constant mode routines = constant x
rate of free mode routines = 1
rate of max-at routines = 1
rate of lowest-at routines = constant lowest-at

end note
postgres --> api : return wide routines current rates
note right #LightBlue
<b>IMP NOTE
Current rates are not stored in redis, but the rate limit modes are instead stored with their respective constants.
Routines get their rate dynamically when they ask for it by a specific calculation algorithm.

end note
alt isWide
api -> postgres : GetNarrowRoutinesRateInEachHostInTheProgram("PROGRAM")

postgres --> api : return current narrow rates in all hosts
loop for each HOST in PROGRAM
api -> api : checkAbidesToEachHostRateLimit()
api -> api: TotalNarrowRoutinesRateInAProgram += (Each HOST current rate)
note right
Condition 1: (Abide to all hosts rate limit)
Program routines always have constant rate limit mode
Suppose the program routine is X, we have to <b>check for every host:
<b>(HostMaxRate)-(TotalNarrowRoutinesRateInHost+TotalWideRoutinesRateInAProgram) >= X constant rate
end note
end
api -> api : checkAbidesToProgramRateLimit()
note right
Condition 2: (abide to program rate limit)
After calculation of Total we have to check for:
<b>(ProgramMaxRate)-(TotalNarrowRoutinesRateInAProgram + TotalWideRoutinesRateInAProgram) >= X constant rate
end note

alt CONDITIONS 1 && 2
api -> postgres: updateRunStateFromToQueueToQueued("ROUTINE")
alt isEagerRun
api -> mainq: publishPointerWithHighPriority()
else isLazyRun
api -> mainq: publishPointer()
end

end
else isNarrow
api -> postgres : GetNarrowRoutinesRate("HOST")

postgres --> api : return current narrow rates in host

api -> api : checkAbidesToHostRateLimit()
note right
Condition 1: (Abide to host max rate limit)
Suppose the narrow routine is X, we have to <b>check for target host:
<b>(HostMaxRate)-(TotalNarrowRoutinesRateInHost+TotalWideRoutinesRateInAProgram) >= :
(X constant rate | X max-at constant | X lowest-at constant | 1 if X is free)
end note
alt isShort
api -> api : checkAbidesToShortRateLimit()
note right
Condition 2.a: (Abide to short rate limits)
Suppose the program routine is X, we have to <b>check for target host:
<b>(ShortMaxRate)-(TotalShortRoutinesRateInHost) >= :
(X constant rate | X max-at constant | X lowest-at constant | 1 if X is free)
end note
else isLong
api -> api : checkAbidesToLongRateLimit()
note right
Condition 2.b: (Abide to long rate limits)
Suppose the program routine is X, we have to <b>check for target host:
<b>(LongMaxRate)-(TotalLongRoutinesRateInHost) >= :
(X constant rate | X max-at constant | X lowest-at constant | 1 if X is free)
end note
end
api -> postgres : GetNarrowRoutinesRateInEachHostInTheProgram("PROGRAM")
postgres --> api : return current narrow rates in all hosts

loop for each HOST in PROGRAM
api -> api: TotalNarrowRoutinesRateInAProgram += (Each HOST current rate)

end
api -> api : checkAbidesToProgramRateLimit()
note right
Condition 3: (abide to program rate limit)
After calculation of Total we have to check for:
<b>(ProgramMaxRate)-(TotalNarrowRoutinesRateInAProgram + TotalWideRoutinesRateInAProgram) >= :
(X constant rate | X max-at constant | X lowest-at constant | 1 if X is free)
end note
alt CONDITIONS 1 && 2 && 3

api -> postgres: updateRunStateFromToQueueToQueued
alt isEagerRun
api -> mainq: publishPointerWithHighPriority()
else isLazyRun
api -> mainq: publishPointer()
end
end
end

@enduml