@startuml
actor "User" as user
box "Central Server"
participant "Central Service" as api
database postgres
database redis
end box
box "Worker Server"
participant "Execution Worker" as worker
end box

user -> api : resume(X)
api -> postgres : updateRequestedStateToResumed()
api -> redis : insertHeartbeat(X)
api --> user : 204
... few seconds ...
ref over worker : routine-queries-status-a-rate

@enduml