@startuml
actor "User" as user
box "Central Server"
participant "<b>Central Service" as api
participant "Quartz Scheduler" as scheduler
database postgres

autonumber "<b>[00]"
user -> api : initiate type:SCHEDULED run
api -> postgres : store run details

api --> user: return run details
api -> scheduler : scheduleEnqueueOperation(date, routineContext)
scheduler --> api : scheduled
... Some time later:...
scheduler -> api : executeEnqueueJob(routineContext)

ref over api : QUEUED_RUN_INITATION

@enduml