@startuml
actor "User" as user
box "Central Server"
participant "<b>Cental Service" as api
participant "Quartz Scheduler" as scheduler
database postgres

autonumber "<b>[00]"
user -> api : initiate type:SCHEDULED run
api -> postgres : store run details

api --> user: return run details
api -> scheduler : scheduleEnqueue(date, routineContext)
scheduler --> api : scheduled
... Some time later:...
scheduler -> api : executeEnqueueJob(routineContext)

alt isProgramRoutine
ref over api : PROGRAM_QUEUED_RUN_INITATION
else isHostRoutine
ref over api : HOST_QUEUED_RUN_INITATION
end


@enduml