@startuml
actor "User" as user
box "Central Server"
participant "Cental Service" as api
database postgres
database redis
queue "Main Global" as mainq
end box


api -> postgres : GetHighPriorityIfFoundElseOldestRoutineToQueueForAllPrograms()
activate postgres
note right
Here "PROGRAM" is the program which is relative to the action which has caused the sync
So if for example a routine finished in the program X then "X" will be the "PROGRAM" here
end note
postgres --> api: return list of routine run details
deactivate postgres

loop For Each routine run in list
    api -> redis : GetWideRoutinesRate("PROGRAM")
    activate redis
    note right #LightGreen
    <b>VERY IMP NOTE
    When calculating current narrow running rate to determine whether we are able to run a new routine:
    rate of constant mode routines = constant x
    rate of free mode routines = 1
    rate of max-at routines = 1
    rate of lowest-at routines = constant lowest-at

    end note
    redis --> api : return wide routines current rates
    deactivate redis

    note right #LightBlue
    <b>IMP NOTE
    Current rates are not stored in redis, but the rate limit modes are instead stored with their respective constants.
    Routines get their rate dynamically when they ask for it by a specific calculation algorithm.

    end note

    alt isWide
        loop for each HOST in PROGRAM
            api -> redis : GetNarrowRoutinesRate("HOST")
            activate redis
            redis --> api : return current rates
            deactivate redis

            api -> api: TotalNarrowRoutinesRateInAProgram += (HOST current rate)
            ' internal computation (api stays active)
            activate api
            api -> api : checkAbidesToEachHostRateLimit()
            note right
            Condition 1: (Abide to all hosts rate limit)
            Program routines always have constant rate limit mode
            Suppose the program routine is X, we have to <b>check for every host:
            <b>(HostMaxRate)-(TotalNarrowRoutinesRateInHost+TotalWideRoutinesRateInAProgram) >= X constant rate
            end note
            deactivate api
        end

        api -> api : checkAbidesToProgramRateLimit()
        activate api
        note right
        Condition 2: (abide to program rate limit)
        After calculation of Total we have to check for:
        <b>(ProgramMaxRate)-(TotalNarrowRoutinesRateInAProgram + TotalWideRoutinesRateInAProgram) >= X constant rate
        end note
        deactivate api

        alt CONDITIONS 1 && 2
            api -> postgres: updateRunStateFromToQueueToQueued
            activate postgres
            postgres --> api : ok
            deactivate postgres

            api -> redis : addWideRoutineRateToProgram("PROGRAM")
            activate redis
            redis --> api : ok
            deactivate redis

            alt isEagerRun
                api -> mainq: publishPointerWithHighPriority()
                activate mainq
                mainq --> api : ack
                deactivate mainq
            else isLazyRun
                api -> mainq: publishPointer()
                activate mainq
                mainq --> api : ack
                deactivate mainq
            end
        end
    else isNarrow
        api -> redis : GetNarrowRoutinesRate("HOST")
        activate redis
        redis --> api : return current rates
        deactivate redis

        api -> api : checkAbidesToHostRateLimit()
        activate api
        note right
        Condition 1: (Abide to host max rate limit)
        Suppose the narrow routine is X, we have to <b>check for target host:
        <b>(HostMaxRate)-(TotalNarrowRoutinesRateInHost+TotalWideRoutinesRateInAProgram) >= :
        (X constant rate | X max-at constant | X lowest-at constant | 1 if X is free)
        end note
        deactivate api

        alt isShort
            api -> api : checkAbidesToShortRateLimit()
            activate api
            note right
            Condition 2.a: (Abide to short rate limits)
            Suppose the program routine is X, we have to <b>check for target host:
            <b>(ShortMaxRate)-(TotalShortRoutinesRateInHost) >= :
            (X constant rate | X max-at constant | X lowest-at constant | 1 if X is free)
            end note
            deactivate api
        else isLong
            api -> api : checkAbidesToLongRateLimit()
            activate api
            note right
            Condition 2.b: (Abide to long rate limits)
            Suppose the program routine is X, we have to <b>check for target host:
            <b>(LongMaxRate)-(TotalLongRoutinesRateInHost) >= :
            (X constant rate | X max-at constant | X lowest-at constant | 1 if X is free)
            end note
            deactivate api
        end

        loop for each HOST in PROGRAM
            api -> redis : GetNarrowRoutinesRate("HOST")
            activate redis
            redis --> api : return current rates
            deactivate redis

            api -> api: TotalNarrowRoutinesRateInAProgram += (HOST current rate)
        end

        api -> api : checkAbidesToProgramRateLimit()
        activate api
        note right
        Condition 3: (abide to program rate limit)
        After calculation of Total we have to check for:
        <b>(ProgramMaxRate)-(TotalNarrowRoutinesRateInAProgram + TotalWideRoutinesRateInAProgram) >= :
        (X constant rate | X max-at constant | X lowest-at constant | 1 if X is free)
        end note
        deactivate api

        alt CONDITIONS 1 && 2 && 3
            api -> postgres: updateRunStateFromToQueueToQueued
            activate postgres
            postgres --> api : ok
            deactivate postgres

            api -> redis : addNarrowRoutineRateToHost("HOST")
            activate redis
            redis --> api : ok
            deactivate redis

            alt isEagerRun
                api -> mainq: publishPointerWithHighPriority()
                activate mainq
                mainq --> api : ack
                deactivate mainq
            else isLazyRun
                api -> mainq: publishPointer()
                activate mainq
                mainq --> api : ack
                deactivate mainq
            end
        end
    end
end

@enduml
